### PR TITLE
Upgrade from Junit 4.x to Junit 5.4.0

### PR DESCRIPTION
**Pull request by marouaneunix**
I loved the kata 👍, so i said why not create a PR to upgrade junit to 5.x 😁
How its look with _DisplayName_ annotation
image

### CODE REVIEW

**Comment by vmzakharov** [comment]
Thank you for your contribution! (and my apologies for the delayed response). Looks good, just two requests, please:

- bump up to the latest the version of pitest, junit 5, and the pitest junit 5 plugin (I use this as a reference: https://github.com/pitest/pitest-junit5-plugin)
- in this case the test display names appear to be somewhat redundant as the test method names are pretty descriptive. Sometimes the display names are inconsistent with the method manes names (e.g., removing leading and trailing spaces test). Rather than fixing the names and making an effort to keep them consistent, I would just remove them.

If you are OK with making the changes, I will be happy to merge and I promise it will be done quickly this time! 😀 Thank you again.

**Review by vmzakharov — CHANGES_REQUESTED** [review]
Thank you for your contribution! (and my apologies for the delayed response). Looks good, just two requests, please:

- bump up to the latest the version of pitest, junit 5, and the pitest junit 5 plugin (I use this as a reference: https://github.com/pitest/pitest-junit5-plugin)
- in this case the test display names appear to be somewhat redundant as the test method names are pretty descriptive. Sometimes the display names are inconsistent with the method manes names (e.g., removing leading and trailing spaces test). Rather than fixing the names and making an effort to keep them consistent, I would just remove them.

If you are OK with making the changes, I will be happy to merge and I promise it will be done quickly this time! 😀 Thank you again.

**Comment by marouaneunix** [comment]
@vmzakharov I hope you find the changes I've made helpful.

**Review by vmzakharov — CHANGES_REQUESTED** [review]
Hi - thank you, looks good! Thank you for addressing the suggestions! Just one thing - with the latest commit you seem to have moved opening braces to the same line as the method headers for some of the methods. It didn't look like that was the case with the previous commit. This is inconsistent with the rest of the code where the method header is visually separated from the method’s body as the opening brace is on the new line. Any chance you can recover the formatting (putting the opening braces on the separate line)? Meanwhile this tells me that I should add checkstyle to the project to help avoid these kinds of issues.

**Comment by marouaneunix** [comment]
Hi @vmzakharov Thank you for your feedback, i maked the change in the current commit [Fix PR feedback](https://github.com/vmzakharov/mutate-test-kata/pull/4/commits/7f63090d837d86daf9e9499a88f3c6a0e2b53398) also i have get the last update from origin and do some change for the checkstyle

**Comment by vmzakharov** [comment]
@marouaneunix - Thank you for your contribution!

**Pull request merged**
